# Generated by Django 4.1.4 on 2023-09-24 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_season_alter_team_options_round_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='away',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='core.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='core.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='core.round'),
        ),
        migrations.AlterField(
            model_name='round',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.season'),
        ),
        migrations.AlterModelTable(
            name='match',
            table='match',
        ),
        migrations.AlterModelTable(
            name='round',
            table='round',
        ),
        migrations.AlterModelTable(
            name='season',
            table='season',
        ),
        migrations.AlterModelTable(
            name='team',
            table='team',
        ),
    ]
