# Generated by Django 4.1.4 on 2023-10-01 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_team_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='first_match',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='round',
            name='last_match',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='goals_away',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='goals_home',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(default='SCHEDULED', max_length=255),
        ),
    ]
